/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
import GameView from "./script/GameView"
import StartGameView from "./scene/StartGameView"
import Dici from "./script/Dici"
import Normal from "./script/Normal"

export default class GameConfig {
    static init() {
        //注册Script或者Runtime引用
        let reg = Laya.ClassUtils.regClass;
		reg("script/GameView.js",GameView);
		reg("scene/StartGameView.js",StartGameView);
		reg("script/Dici.js",Dici);
		reg("script/Normal.js",Normal);
    }
}
GameConfig.width = 750;
GameConfig.height = 1334;
GameConfig.scaleMode ="fixedwidth";
GameConfig.screenMode = "none";
GameConfig.alignV = "top";
GameConfig.alignH = "left";
GameConfig.startScene = "StartGameView.scene";
GameConfig.sceneRoot = "";
GameConfig.debug = false;
GameConfig.stat = false;
GameConfig.physicsDebug = false;
GameConfig.exportSceneToJson = true;

GameConfig.init();
